apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  namespace: voting

  spec:
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: dockersamples/examplevotingapp_result
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: voting

spec:
  selector:
    app: myapp
  ports:
  - port: 8081
    targetPort: 80

