apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: voting
spec:
  selector:
    app: db
  ports:
  - port: 5432
    targetPort: 5432
    name:  "db-service"
---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: voting
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    name: "redis-service"
         
---

apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: voting
spec:
  selector:
    app: result
  ports:
  - port: 8081
    targetPort: 80
  # type: LoadBalancer
---

apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: voting
spec:
  selector:
    app: vote
  ports:
  - port: 8080
    targetPort: 80
  # type: LoadBalancer

