apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: voting
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: dockersamples/examplevotingapp_worker
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        